// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bot.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	bot.proto

It has these top-level messages:
	Command
	Module
	ModulesRequest
	ModulesResponse
	Channel
	ChannelsRequest
	ChannelsResponse
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Enabled  bool   `protobuf:"varint,2,opt,name=enabled" json:"enabled,omitempty"`
	Cooldown string `protobuf:"bytes,3,opt,name=cooldown" json:"cooldown,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Command) GetCooldown() string {
	if m != nil {
		return m.Cooldown
	}
	return ""
}

type Module struct {
	Name            string              `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Commands        map[string]*Command `protobuf:"bytes,2,rep,name=commands" json:"commands,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnabledCommands map[string]bool     `protobuf:"bytes,3,rep,name=enabled_commands,json=enabledCommands" json:"enabled_commands,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *Module) Reset()                    { *m = Module{} }
func (m *Module) String() string            { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()               {}
func (*Module) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Module) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Module) GetCommands() map[string]*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *Module) GetEnabledCommands() map[string]bool {
	if m != nil {
		return m.EnabledCommands
	}
	return nil
}

type ModulesRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
}

func (m *ModulesRequest) Reset()                    { *m = ModulesRequest{} }
func (m *ModulesRequest) String() string            { return proto.CompactTextString(m) }
func (*ModulesRequest) ProtoMessage()               {}
func (*ModulesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ModulesRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type ModulesResponse struct {
	Modules map[string]*Module `protobuf:"bytes,1,rep,name=modules" json:"modules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ModulesResponse) Reset()                    { *m = ModulesResponse{} }
func (m *ModulesResponse) String() string            { return proto.CompactTextString(m) }
func (*ModulesResponse) ProtoMessage()               {}
func (*ModulesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ModulesResponse) GetModules() map[string]*Module {
	if m != nil {
		return m.Modules
	}
	return nil
}

type Channel struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// map<string, Module> modules = 2;
	EnabledModules map[string]bool `protobuf:"bytes,3,rep,name=enabled_modules,json=enabledModules" json:"enabled_modules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *Channel) Reset()                    { *m = Channel{} }
func (m *Channel) String() string            { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()               {}
func (*Channel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetEnabledModules() map[string]bool {
	if m != nil {
		return m.EnabledModules
	}
	return nil
}

type ChannelsRequest struct {
}

func (m *ChannelsRequest) Reset()                    { *m = ChannelsRequest{} }
func (m *ChannelsRequest) String() string            { return proto.CompactTextString(m) }
func (*ChannelsRequest) ProtoMessage()               {}
func (*ChannelsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ChannelsResponse struct {
	Channels map[string]*Channel `protobuf:"bytes,1,rep,name=channels" json:"channels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ChannelsResponse) Reset()                    { *m = ChannelsResponse{} }
func (m *ChannelsResponse) String() string            { return proto.CompactTextString(m) }
func (*ChannelsResponse) ProtoMessage()               {}
func (*ChannelsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ChannelsResponse) GetChannels() map[string]*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

func init() {
	proto.RegisterType((*Command)(nil), "grpc.Command")
	proto.RegisterType((*Module)(nil), "grpc.Module")
	proto.RegisterType((*ModulesRequest)(nil), "grpc.ModulesRequest")
	proto.RegisterType((*ModulesResponse)(nil), "grpc.ModulesResponse")
	proto.RegisterType((*Channel)(nil), "grpc.Channel")
	proto.RegisterType((*ChannelsRequest)(nil), "grpc.ChannelsRequest")
	proto.RegisterType((*ChannelsResponse)(nil), "grpc.ChannelsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for BotService service

type BotServiceClient interface {
	Channels(ctx context.Context, in *ChannelsRequest, opts ...grpc1.CallOption) (*ChannelsResponse, error)
	Modules(ctx context.Context, in *ModulesRequest, opts ...grpc1.CallOption) (*ModulesResponse, error)
}

type botServiceClient struct {
	cc *grpc1.ClientConn
}

func NewBotServiceClient(cc *grpc1.ClientConn) BotServiceClient {
	return &botServiceClient{cc}
}

func (c *botServiceClient) Channels(ctx context.Context, in *ChannelsRequest, opts ...grpc1.CallOption) (*ChannelsResponse, error) {
	out := new(ChannelsResponse)
	err := grpc1.Invoke(ctx, "/grpc.BotService/Channels", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) Modules(ctx context.Context, in *ModulesRequest, opts ...grpc1.CallOption) (*ModulesResponse, error) {
	out := new(ModulesResponse)
	err := grpc1.Invoke(ctx, "/grpc.BotService/Modules", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BotService service

type BotServiceServer interface {
	Channels(context.Context, *ChannelsRequest) (*ChannelsResponse, error)
	Modules(context.Context, *ModulesRequest) (*ModulesResponse, error)
}

func RegisterBotServiceServer(s *grpc1.Server, srv BotServiceServer) {
	s.RegisterService(&_BotService_serviceDesc, srv)
}

func _BotService_Channels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).Channels(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BotService/Channels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).Channels(ctx, req.(*ChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_Modules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).Modules(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BotService/Modules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).Modules(ctx, req.(*ModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BotService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.BotService",
	HandlerType: (*BotServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "Channels",
			Handler:    _BotService_Channels_Handler,
		},
		{
			MethodName: "Modules",
			Handler:    _BotService_Modules_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "bot.proto",
}

func init() { proto.RegisterFile("bot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xbb, 0xae, 0xd3, 0x40,
	0x10, 0xd5, 0xda, 0x97, 0x6b, 0xdf, 0xb9, 0x79, 0xb1, 0x24, 0xc8, 0x72, 0x15, 0x0c, 0x45, 0x44,
	0xe1, 0x22, 0x48, 0x11, 0x20, 0x0a, 0x48, 0x14, 0x09, 0x45, 0xd0, 0x38, 0x1f, 0x10, 0x39, 0xf6,
	0x0a, 0x10, 0xf6, 0x6e, 0xb0, 0x9d, 0xa0, 0x54, 0x7c, 0x07, 0x1d, 0x1f, 0x40, 0xc5, 0x17, 0x22,
	0xef, 0xc3, 0xd9, 0x8d, 0xb6, 0x80, 0xce, 0x33, 0x3b, 0xe7, 0xcc, 0x99, 0x33, 0x23, 0xc3, 0xdd,
	0x9e, 0x35, 0xf1, 0xa1, 0x62, 0x0d, 0xc3, 0x37, 0x9f, 0xaa, 0x43, 0x16, 0x6d, 0xc1, 0x5b, 0xb1,
	0xb2, 0x4c, 0x69, 0x8e, 0x31, 0xdc, 0xd0, 0xb4, 0x24, 0x01, 0x9a, 0xa2, 0xd9, 0x5d, 0xc2, 0xbf,
	0x71, 0x00, 0x1e, 0xa1, 0xe9, 0xbe, 0x20, 0x79, 0xe0, 0x4c, 0xd1, 0xcc, 0x4f, 0x54, 0x88, 0x43,
	0xf0, 0x33, 0xc6, 0x8a, 0x9c, 0x7d, 0xa7, 0x81, 0xcb, 0x11, 0x5d, 0x1c, 0xfd, 0x71, 0xe0, 0xf6,
	0x23, 0xcb, 0x8f, 0x05, 0xb1, 0x92, 0x2e, 0x5a, 0x28, 0xef, 0x59, 0x07, 0xce, 0xd4, 0x9d, 0xdd,
	0xcf, 0xc3, 0xb8, 0x15, 0x13, 0x0b, 0x4c, 0x2c, 0x05, 0xd5, 0x6b, 0xda, 0x54, 0xe7, 0xa4, 0xab,
	0xc5, 0x1f, 0x60, 0x24, 0xbb, 0xef, 0x3a, 0xbc, 0xcb, 0xf1, 0x4f, 0x0c, 0xfc, 0x5a, 0x14, 0x99,
	0x34, 0x43, 0x62, 0x66, 0xc3, 0x0d, 0xf4, 0x8d, 0x0a, 0x3c, 0x02, 0xf7, 0x2b, 0x39, 0x4b, 0xa5,
	0xed, 0x27, 0x7e, 0x0a, 0x0f, 0x4e, 0x69, 0x71, 0x24, 0x7c, 0xf6, 0xfb, 0x79, 0x5f, 0x74, 0x91,
	0xa8, 0x44, 0xbc, 0xbd, 0x76, 0x5e, 0xa2, 0x70, 0x09, 0x63, 0x5b, 0x53, 0x0b, 0xe5, 0x58, 0xa7,
	0xf4, 0x35, 0x8e, 0xe8, 0x39, 0x0c, 0x84, 0xfe, 0x3a, 0x21, 0xdf, 0x8e, 0xa4, 0x6e, 0x5a, 0xf3,
	0xb3, 0xcf, 0x29, 0xa5, 0xa4, 0x90, 0x0c, 0x2a, 0x8c, 0x7e, 0x22, 0x18, 0x76, 0xc5, 0xf5, 0x81,
	0xd1, 0x9a, 0xe0, 0x37, 0xe0, 0x95, 0x22, 0x15, 0x20, 0x6e, 0x4a, 0xa4, 0x9b, 0xd2, 0xd5, 0xa9,
	0x58, 0xb8, 0xa2, 0x20, 0xe1, 0x7b, 0xe8, 0xe9, 0x0f, 0x16, 0xe5, 0x91, 0x69, 0x46, 0x4f, 0x67,
	0xd7, 0xe7, 0xf8, 0x8d, 0xc0, 0x5b, 0x09, 0x9d, 0xd6, 0xed, 0x6f, 0x40, 0xad, 0x62, 0xa7, 0xf4,
	0x1a, 0x4b, 0x94, 0x58, 0xb5, 0x45, 0x43, 0xee, 0x80, 0x18, 0xc9, 0xf0, 0x1d, 0x3c, 0xb2, 0x94,
	0xfd, 0x97, 0xed, 0x0f, 0x61, 0x28, 0x3b, 0x2a, 0xdf, 0xa3, 0x5f, 0x08, 0x46, 0x97, 0x9c, 0xb4,
	0xf7, 0x2d, 0xf8, 0xd2, 0x7d, 0xe5, 0xef, 0x33, 0x43, 0xef, 0xc5, 0x60, 0x95, 0x50, 0xe7, 0x2b,
	0x43, 0x7e, 0x70, 0xfa, 0xd3, 0xbf, 0x1f, 0x9c, 0x40, 0x69, 0xaa, 0xe7, 0x3f, 0x00, 0x96, 0xac,
	0xd9, 0x92, 0xea, 0xf4, 0x25, 0x23, 0xf8, 0x15, 0xf8, 0x8a, 0x19, 0x4f, 0xae, 0x55, 0xf1, 0x99,
	0xc2, 0xc7, 0x76, 0xb1, 0x78, 0x01, 0x9e, 0xb4, 0x0e, 0x8f, 0xaf, 0xee, 0x45, 0x00, 0x27, 0xd6,
	0x2b, 0xda, 0xdf, 0xf2, 0x9f, 0xc8, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x09, 0xd6,
	0x8e, 0x51, 0x04, 0x00, 0x00,
}
